<?php

$title = 'Add new todo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('todo', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('todo_sid'));
echo $this->formRow($form->get('priority'));
echo $this->formRow($form->get('project_sid'));
echo $this->formRow($form->get('todo_status_sid'));
echo $this->formRow($form->get('text'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
