<?php
$this->layout()->bodyClass = 'login';
$title = 'Login';
$this->headTitle($title);

$form->setAttribute('action', $_SERVER['REQUEST_URI']);
$form->setAttribute('class', 'form-signin');
$form->prepare();

echo $this->form()->openTag($form);
?>
<h1 class='form-signin-heading'><?php echo $this->escapeHtml($title); ?></h1>
<?php
echo $this->formElement($form->get('user_sid'));
echo $this->formElement($form->get('email'));
echo $this->formElementErrors($form->get('email'));
echo $this->formElement($form->get('password'));
echo $this->formElementErrors($form->get('password'));
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
